-- 插入班级表
insert into t_Class (Class_Id,Class_Name) values(1,'基础班');
insert into t_Class (Class_Id,Class_Name) values(2,'强化班');
insert into t_Class (Class_Id,Class_Name) values(3,'超神班');
insert into t_Class (Class_Id,Class_Name) values(4,'明星班');


-- 插入学生表
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10001,'张三',18,'男',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10002,'李四',19,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10004,'汤姆',15,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10005,'李希',16,'女',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10006,'李莉',16,'女',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10007,'杰克',20,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10008,'露丝',18,'女',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10009,'李雷',17,'男',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10010,'韩梅梅',17,'女',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10011,'麦克',18,'男',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10012,'吉姆',16,'男',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10013,'乔伊',17,'女',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10014,'大卫',18,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10015,'爱丽丝',16,'女',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10016,'托尼',15,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10017,'葛天',28,'男',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10018,'何军',26,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10019,'陈菲',23,'女',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10020,'张三丰',31,'男',1);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (10021,'李世民',21,'男',2);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (20013,'肥猪流',17,'女',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (20014,'碧云天',18,'男',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (20015,'陈美美',16,'女',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (20016,'戴中原',15,'男',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (30013,'林一',17,'女',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (30014,'林二',18,'男',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (30015,'林三',16,'女',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (30016,'林四',15,'男',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (30017,'林五',31,'男',3);
insert into t_Student (Stu_ID,Stu_Name,Stu_Age,Stu_Sex,Class_Name) values (30018,'林六',22,'男',4);


-- 插入部门表
insert into t_Department (Department_ID,Department_Name) values (1,'市场部');
insert into t_Department (Department_ID,Department_Name) values (2,'人事部');
insert into t_Department (Department_ID,Department_Name) values (3,'研发部');

-- 插入员工表
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (101,'李春梅',35,'女',6500,1);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (102,'张桂花',26,'女',4000,1);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (103,'陈丽',28,'女',4500,1);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (104,'林清香',24,'女',4800,1);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (201,'赵丽春',32,'女',6500,2);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (202,'葛天华',25,'女',3500,2);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (203,'林志',27,'男',3800,2);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (204,'陈晓丹',23,'女',4300,2);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (301,'马华疼',32,'男',12000,3);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (302,'雷布斯',28,'男',8000,3);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (303,'周艳红',25,'女',7000,3);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (304,'张天',24,'男',6000,3);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (305,'李志明',20,'男',3500,3);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (105,'张三',23,'男',4600,1);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (205,'李四',25,'男',5600,2);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (306,'马云',35,'男',12000,3);
insert into t_Staff (Staff_Num,Staff_Name,Staff_Age,Staff_Sex,Staff_Salary, Department_Name) values (106,'李红',20,'男',1800,2);



-- 插入地区表
insert into t_Region (Region_ID,Region_Name) values (1,'未知');
insert into t_Region (Region_ID,Region_Name) values (2,'德玛西亚');
insert into t_Region (Region_ID,Region_Name) values (3,'祖安');
insert into t_Region (Region_ID,Region_Name) values (4,'诺克萨斯');
insert into t_Region (Region_ID,Region_Name) values (5,'弗雷尔卓德');
insert into t_Region (Region_ID,Region_Name) values (6,'班德尔城');
insert into t_Region (Region_ID,Region_Name) values (7,'艾欧尼亚');
insert into t_Region (Region_ID,Region_Name) values (8,'恕瑞玛');
insert into t_Region (Region_ID,Region_Name) values (9,'瓦洛兰');
insert into t_Region (Region_ID,Region_Name) values (10,'皮尔吉沃特');
insert into t_Region (Region_ID,Region_Name) values (11,'虚空世界');
insert into t_Region (Region_ID,Region_Name) values (12,'暗影岛');

-- 插入英雄表
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (1,'黑暗之女','安妮','女',4800,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (2,'岩雀','塔利亚','女',6300,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (3,'迷失之牙','纳尔','男',6300,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (4,'虚空行者','卡萨丁','男',3150,11);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (5,'德玛西亚之翼','奎因','女',6300,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (6,'暗影之拳','阿卡丽','女',3150,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (7,'远古巫灵','泽拉斯','男',4800,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (8,'冰霜女巫','丽桑卓','女',6300,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (9,'雷霆咆哮','沃利贝尔','男',4800,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (10,'爆破鬼才','吉格斯','男',6300,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (11,'仙灵女巫','璐璐','女',4800,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (12,'潮汐海灵','菲兹','女',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (13,'冰晶凤凰','艾尼维亚','女',4800,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (14,'策士统领','斯维因','男',4800,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (15,'祖安狂人','蒙多','男',1350,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (16,'巨魔之王','特朗德尔','男',3150,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (17,'蒸汽机器人','布里茨','男',3150,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (18,'狂暴之心','凯南','男',4800,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (19,'德玛西亚之力','盖伦','男',3150,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (20,'龙血武姬','希瓦娜','女',4800,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (21,'诡术妖姬','乐芙兰','女',4800,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (22,'猩红收割者','费拉基米尔','男',3150,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (23,'牛头酋长','阿利斯塔','男',1350,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (24,'众星之子','索拉卡','女',450,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (25,'雪人骑士','努努','男',450,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (26,'寒冰射手','艾希','女',450,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (27,'虚空之眼','维克兹','女',6300,11);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (28,'虚空恐惧','科加斯','男',3150,11);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (29,'刀锋意志','艾瑞莉娅','女',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (30,'战争女神','希维尔','女',450,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (31,'机械先驱','维克托','男',4800,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (32,'卡牌大师','崔斯特','男',6300,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (33,'铁铠冥魂','莫德凯撒','男',3150,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (34,'无极剑圣','易','男',450,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (35,'光辉女郎','拉克丝','女',3150,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (36,'祖安怒兽','沃里克','男',3150,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (37,'九尾妖狐','阿狸','女',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (38,'末日使者','费德提克','男',1350,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (39,'迅捷斥候','提莫','男',6300,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (40,'炼金术士','辛吉德','男',1350,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (41,'木乃伊之殇','阿木木','男',1350,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (42,'瘟疫之源','图奇','男',4800,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (43,'生化魔人','扎克','男',4800,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (44,'深渊巨口','克格莫','男',4800,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (45,'时光守护者','基兰','男',450,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (46,'魂锁典狱长','锤石','男',6300,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (47,'唤潮鲛姬','娜美','女',4800,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (48,'沙漠死神','内瑟斯','男',3150,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (49,'蜘蛛女皇','伊莉丝','女',4800,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (50,'亡灵战神','塞恩','男',1350,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (51,'复仇之矛','卡莉斯塔','女',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (52,'酒桶','古拉加斯','男',3150,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (53,'狂野女猎手','奈德丽','女',6300,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (54,'深海泰坦','诺提勒斯','男',4800,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (55,'麦林炮手','崔丝塔娜','女',1350,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (56,'符文法师','瑞兹','男',450,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (57,'熔岩巨兽','墨菲特','男',1350,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (58,'皮城女警','凯特琳','女',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (59,'天启者','卡尔玛','女',3150,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (60,'邪恶小法师','维迦','男',1350,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (61,'风暴之怒','迦娜','女',1350,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (62,'河流之王','塔姆','男',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (63,'披甲龙龟','拉莫斯','男',3150,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (64,'时间刺客','艾克','男',6300,3);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (65,'兽灵行者','乌迪尔','男',3150,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (66,'北地之怒','瑟庄妮','女',4800,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (67,'机械公敌','兰博','男',4800,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (68,'荣耀提刑官','德莱文','男',6300,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (69,'费雷尔卓德之心','布隆','男',6300,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (70,'海洋之灾','普朗克','男',3150,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (71,'无双剑姬','菲奥娜','女',6300,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (72,'武器大师','贾克斯','男',3150,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (73,'战争之影','赫卡里姆','男',6300,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (74,'盲僧','李青','男',4800,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (75,'永猎双子','千珏','女',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (76,'永恒梦魇','魔腾','男',4800,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (77,'圣枪游侠','卢锡安','男',6300,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (78,'圣锤之毅','波比','女',450,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (79,'狂战士','奥拉夫','男',1350,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (80,'荒漠屠夫','雷克顿','男',4800,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (81,'虚空遁地兽','雷克塞','女',6300,11);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (82,'放逐之刃','瑞文','女',6300,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (83,'傲之追猎者','雷恩加尔','男',6300,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (84,'刀锋之影','泰隆','男',6300,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (85,'恶魔小丑','萨科','男',4800,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (86,'蛮族之王','泰达米尔','男',4800,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (87,'惩戒之箭','韦鲁斯','男',4800,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (88,'瓦洛兰之盾','塔里克','男',3150,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (89,'无畏战车','厄加特','男',1350,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (90,'齐天大圣','孙悟空','男',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (91,'皮城执法官','蔚','女',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (92,'牧魂人','约里克','男',3150,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (93,'逆羽','霞','女',6300,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (94,'戏命师','烬','男',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (95,'影流之主','劫','男',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (96,'发条魔灵','奥利安娜','女',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (97,'海兽祭司','俄洛伊','女',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (98,'星界游神','巴德','男',6300,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (99,'铸星龙王','奥莉瑞安-索尔','男',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (100,'诺克萨斯之手','德莱厄斯','男',6300,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (101,'青钢影','卡蜜尔','女',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (102,'德玛西亚皇子','嘉文四世','男',4800,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (103,'正义巨像','加里奥','男',3150,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (104,'死亡颂唱者','卡尔萨斯','男',4800,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (105,'翠神','艾翁','男',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (106,'堕落天使','莫甘娜','女',1350,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (107,'扭曲树精','茂凯','男',4800,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (108,'德邦总管','赵信','男',3150,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (109,'暮光之眼','慎','男',4800,12);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (110,'暗裔剑魔','亚托克斯','男',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (111,'荆棘之兴','婕拉','女',4800,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (112,'影流之镰','凯隐','男',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (113,'未来守护者','杰斯','男',4800,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (114,'疾风剑豪','亚索','男',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (115,'暴怒骑士','克烈','男',6300,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (116,'魔蛇之拥','卡西奥佩娅','女',4800,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (117,'沙漠皇帝','阿兹尔','男',6300,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (118,'不祥之刃','卡特琳娜','女',3150,4);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (119,'英勇投弹手','库奇','男',6300,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (120,'赏金猎人','厄运小姐','女',3150,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (121,'曙光女神','蕾欧娜','女',4800,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (122,'法外狂徒','格雷福斯','男',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (123,'复仇烈焰','布兰德','男',4800,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (124,'审判天使','凯尔','女',450,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (125,'大发明家','黑默丁格','男',3150,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (126,'暗黑元首','辛德拉','女',6300,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (127,'水晶先锋','斯卡纳','男',3150,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (128,'痛苦之拥','伊芙琳','女',1350,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (129,'暮光星灵','佐伊','女',6300,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (130,'暴走萝莉','金克斯','女',6300,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (131,'探险家','伊泽瑞尔','男',4800,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (132,'虚空掠夺者','卡兹克','男',6300,11);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (133,'琴瑟仙女','娑娜','女',3150,7);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (134,'暗夜射手','薇恩','女',4800,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (135,'山隐之焰','奥恩','男',6300,5);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (136,'战争之王','潘森','男',3150,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (137,'虚空先知','马尔扎哈','男',4800,8);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (138,'皎月女神','黛安娜','女',6300,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (139,'幻翎','洛','男',6300,9);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (140,'虚空之女','卡莎','女',6300,11);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (141,'血港鬼影','派克','男',7800,10);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (142,'万花通灵','妮蔻','女',7800,1);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (143,'解脱者','塞拉斯','男',7800,2);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (144,'魔法猫咪','悠米','女',7800,6);
insert into t_Hero (Hero_ID,Hero_Title,Hero_Name,Hero_Sex,Hero_Price, Hero_Region) values (145,'元素女皇','奇亚娜','女',7800,1);
